### PR TITLE
Expiration change

### PR DESCRIPTION
**Pull request by tomondre**

### CODE REVIEW

**Comment by tomondre** [comment]
Needed for the frontend cuz it is annoying right now to log in each 30 minutes

**Review by KhaledHammoun — APPROVED** [review]

**Review by KhaledHammoun — CHANGES_REQUESTED** [review]
That can be changed locally in the application-local file and not in Prod. They are not testing in Prod I guess

**Comment by tomondre** [comment]
Good point. :D

**Comment by tomondre** [comment]
The cloud service is also used for development, so there is no need to run the backend on localhost + response times are way faster cuz of sql executions

**Review by KhaledHammoun — APPROVED** [review]

**Pull request merged**
